# Netlify configuration for talkinsecret.com
# Sicherheit, Performance und Routing
[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

    [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "PUBLIC_AUDIO_SECRET_KEY"

# HINZUGEFÜGT: Dieser Block stellt sicher, dass die Audio-Dateien
# für die stream-audio Funktion verfügbar sind.
[functions]
  included_files = ["_audio_files/**"]

[dev]
  framework = "astro"
  targetPort = 4321
  port = 8888      # Der Port, auf dem Netlify Dev läuft
  publish = "dist" # Das Verzeichnis, das Netlify Dev bereitstellt

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' https://www.youtube.com https://open.spotify.com https://cdnjs.cloudflare.com 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-src https://www.youtube.com https://open.spotify.com; require-trusted-types-for 'script'; frame-ancestors 'none';"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Cross-Origin-Opener-Policy = "same-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), fullscreen=(self)"